// Dungeonslayers 4 (DS4) - Zaubersprueche
// Quelle: regeln/Dungeonslayers4.pdf (kostenloses Regelwerk, dungeonslayers.net)
//   - Darstellungsschema & Zugangsliste der Heiler:     PDF S. 58 (Buch S. 48)
//   - Zugangslisten Zauberer & Schwarzmagier:           PDF S. 59 (Buch S. 49)
//   - Liste der Zaubersprueche (alphabetisch, Werte):   PDF S. 60-87 (Buch S. 50-77)
//   - Magieregeln (Zaubern / Zielzauber / Abklingzeit): PDF S. 56-57 (Buch S. 46-47)
//
// Alle Effekttexte sind KURZ PARAPHRASIERT (keine Volltext-Uebernahme aus dem Regelwerk).
// Zahlenwerte (Preis, ZB, Dauer, Distanz, Abklingzeit) sind exakt aus dem Regelwerk uebernommen.
//
// ---------------------------------------------------------------------------
// DS4_ZAUBER
//   name                 : Name des Zauberspruchs
//   typ                  : 'normal' = normaler Zauber -> Probe auf Zaubern    (GEI+AU+ZB-PA)
//                          'ziel'   = Zielzauber      -> Probe auf Zielzauber (GEI+GE+ZB-PA)
//                          (im Buch durch das Buch- bzw. Strahlensymbol am Spruchkopf markiert)
//   geistesbeeinflussend : true = im Buch gesondert markiert (Buchsymbol mit "!"); Untote u.ae.
//                          sind dagegen immun, das Talent "Manipulator" gibt einen Bonus darauf.
//   zugang               : [{ klasse, stufe }] - ab welcher Charakterstufe die jeweilige
//                          Zauberwirker-Klasse den Spruch erlernen darf.
//                          klasse ist 'heiler' | 'zauberer' | 'schwarzmagier'.
//                          Ein Spruch auf mehreren Klassenlisten hat mehrere Eintraege
//                          (Quelle: die Zugangslisten auf PDF S. 58-59).
//   preis                : Kaufpreis in Goldmuenzen (GM)
//   zb                   : Zauberbonus auf die Probe (String, da auch Formeln vorkommen,
//                          z.B. '-(GEI+VE)/2 des Ziels')
//   dauer                : Wirkungszeit des Zaubers
//   distanz              : max. Entfernung zum Ziel ('Selbst' = nur der Zauberwirker)
//   abklingzeit          : Dauer, die der Zauber nach erfolgreichem Wirken gesperrt ist
//   effekt               : kurze mechanische Beschreibung (paraphrasiert)
//   seite                : PDF-Seite der Spruchbeschreibung (Buchseite = PDF-Seite - 10)
//
// VALIDIERUNG: Ein Zauberwirker darf einen Spruch erlernen, wenn seine Klasse in `zugang`
// gelistet ist und seine Stufe >= der dortigen `stufe` ist (PDF S. 19/58). Heldenklassen
// behalten den Zugang ihrer Grundklasse. Pro Stufenaufstieg darf ein Zauberwirker neue
// Sprueche erlernen, deren Zugangsstufen zusammen seine neue Charakterstufe ergeben.
// ---------------------------------------------------------------------------
//
// Dungeonslayers wurde geschaffen von Christian Kennig ((c) 2011, Burning Books, Berlin).
// Texte und Regelmechaniken stehen unter CC BY-NC-SA 4.0 - diese abgeleitete Datei
// daher ebenfalls: https://creativecommons.org/licenses/by-nc-sa/4.0/deed.de

const DS4_ZAUBER_TYPEN = { normal: 'Normaler Zauber', ziel: 'Zielzauber' };

// Kampfwert-Schluessel der Probe, die fuer den jeweiligen Zaubertyp gewuerfelt wird.
const DS4_ZAUBER_PROBE = { normal: 'zaubern', ziel: 'zielzauber' };

const DS4_ZAUBER = [
    {
        name: 'Allheilung',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 10 }],
        preis: 650,
        zb: '+0',
        dauer: 'Augenblicklich',
        distanz: 'Berühren',
        abklingzeit: '24 Stunden',
        effekt: 'Heilt sämtliche Verletzungen restlos und narbenfrei; abgetrennte Gliedmaßen lassen sich wieder anfügen, sofern sie höchstens W20 Stunden ab sind.',
        arten: ['heilung'],
        seite: 60
    },
    {
        name: 'Arkanes Schwert',
        typ: 'normal',
        zugang: [{ klasse: 'schwarzmagier', stufe: 8 }, { klasse: 'zauberer', stufe: 10 }],
        preis: 920,
        zb: '+0',
        dauer: 'VE x 2 Kampfrunden',
        distanz: 'Radius von VE Meter',
        abklingzeit: '24 Stunden',
        effekt: 'Ein selbstständig kämpfendes Lichtschwert erscheint im Radius von VE Metern und folgt gedanklichen Kampfbefehlen. Alle Kampfwerte = Stufe +10, Laufen = doppeltes Laufen des Zauberwirkers.',
        seite: 60
    },
    {
        name: 'Balancieren',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 2 }, { klasse: 'schwarzmagier', stufe: 6 }, { klasse: 'zauberer', stufe: 3 }],
        preis: 45,
        zb: '-2',
        dauer: 'Bis Strecke zurückgelegt',
        distanz: 'Berühren',
        abklingzeit: '10 Kampfrunden',
        effekt: 'Das Ziel balanciert mit vollem Laufen-Wert sicher über Seile u.ä., bis es die doppelte Laufen-Strecke zurückgelegt hat.',
        seite: 60
    },
    {
        name: 'Bannen',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 8 }, { klasse: 'schwarzmagier', stufe: 14 }, { klasse: 'zauberer', stufe: 18 }],
        preis: 255,
        zb: '-(KÖR+AU)/2 der Wesenheit',
        dauer: 'Augenblicklich',
        distanz: 'Radius von VE x 2 Meter',
        abklingzeit: '100 Kampfrunden',
        effekt: 'Vernichtet feindliche Dämonen, Elementare und Untote im Radius, maximal Stufe/2 Wesenheiten. Jeder misslungene Bannversuch erschwert den nächsten um 2.',
        arten: ['untot'],
        seite: 60
    },
    {
        name: 'Blenden',
        typ: 'ziel',
        zugang: [{ klasse: 'heiler', stufe: 1 }, { klasse: 'zauberer', stufe: 5 }],
        preis: 10,
        zb: '-(AGI+AU)/2 des Ziels',
        dauer: 'Probenergebnis in Kampfrunden',
        distanz: 'VE x 5 Meter',
        abklingzeit: '5 Kampfrunden',
        effekt: 'Blendet ein Ziel (keine Abwehr erlaubt): -8 auf alle Handlungen, die Sehen erfordern. Wirkt auch auf augenlose Untote, nicht auf Blinde.',
        seite: 61
    },
    {
        name: 'Blitz',
        typ: 'ziel',
        zugang: [{ klasse: 'heiler', stufe: 10 }, { klasse: 'schwarzmagier', stufe: 7 }, { klasse: 'zauberer', stufe: 7 }],
        preis: 310,
        zb: '+3',
        dauer: 'Augenblicklich',
        distanz: 'VE x 10 Meter',
        abklingzeit: '1 Kampfrunde',
        effekt: 'Ein Blitz trifft einen Gegner; Schaden = Probenergebnis. Gegner in Metallrüstung dürfen keine Abwehr würfeln.',
        arten: ['blitz', 'elementar'],
        seite: 61
    },
    {
        name: 'Blut kochen',
        typ: 'ziel',
        zugang: [{ klasse: 'schwarzmagier', stufe: 13 }, { klasse: 'zauberer', stufe: 17 }],
        preis: 1580,
        zb: '-(KÖR+AU)/2 des Ziels',
        dauer: 'Augenblicklich',
        distanz: 'VE Meter',
        abklingzeit: '24 Stunden',
        effekt: 'Das Blut des Ziels kocht: doppeltes Probenergebnis als Schaden, Abwehr ohne Panzerungsboni. Gegen blutlose Wesen nicht einsetzbar.',
        seite: 61
    },
    {
        name: 'Botschaft',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 8 }, { klasse: 'schwarzmagier', stufe: 8 }, { klasse: 'zauberer', stufe: 6 }],
        preis: 510,
        zb: '+0',
        dauer: 'Bis ausformuliert',
        distanz: 'VE x 5 Kilometer',
        abklingzeit: '24 Stunden',
        effekt: 'Ein geisterhaftes Abbild des Zaubernden erscheint bei einem bekannten Wesen in Reichweite und spricht bis zu VE x 2 Wortsilben.',
        seite: 61
    },
    {
        name: 'Duftnote',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 1 }, { klasse: 'schwarzmagier', stufe: 2 }, { klasse: 'zauberer', stufe: 1 }],
        preis: 10,
        zb: '+0',
        dauer: 'Probenergebnis in Minuten',
        distanz: 'Berühren',
        abklingzeit: '100 Kampfrunden',
        effekt: 'Versieht das Ziel mit einem angenehmen oder unangenehmen Geruch: +2 bzw. -2 auf dessen soziale Proben.',
        seite: 63
    },
    {
        name: 'Durchlässig',
        typ: 'normal',
        zugang: [{ klasse: 'schwarzmagier', stufe: 12 }, { klasse: 'zauberer', stufe: 10 }],
        preis: 920,
        zb: '-4',
        dauer: 'VE/2 Kampfrunden',
        distanz: 'Selbst',
        abklingzeit: '24 Stunden',
        effekt: 'Der Zauberwirker samt Ausrüstung wird für VE/2 Kampfrunden durchlässig und kann durch nichtmagische, unbelebte Objekte schreiten.',
        seite: 63
    },
    {
        name: 'Durchsicht',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 7 }, { klasse: 'schwarzmagier', stufe: 3 }, { klasse: 'zauberer', stufe: 3 }],
        preis: 280,
        zb: '-2',
        dauer: 'VE Kampfrunden',
        distanz: 'Selbst',
        abklingzeit: '24 Stunden',
        effekt: 'Der Zauberwirker sieht VE/2 Meter weit durch nichtmagische, unbelebte Objekte.',
        seite: 63
    },
    {
        name: 'Dämonen beschwören',
        typ: 'normal',
        zugang: [{ klasse: 'schwarzmagier', stufe: 10 }, { klasse: 'zauberer', stufe: 17 }],
        preis: 1190,
        zb: '-(KÖR+AU) des Dämonen und +BB',
        dauer: 'VE x 2 Stunden',
        distanz: 'Radius von VE Meter',
        abklingzeit: '24 Stunden',
        effekt: 'Beschwört einen frei wählbaren Dämon (Flugfähigkeit erschwert die Probe). Er muss VE Aufträge erfüllen, bevor er zurückkehren darf, und kann nur auf Befehl angreifen.',
        seite: 61
    },
    {
        name: 'Ebenentor',
        typ: 'normal',
        zugang: [{ klasse: 'schwarzmagier', stufe: 16 }, { klasse: 'zauberer', stufe: 18 }],
        preis: 2580,
        zb: '-8',
        dauer: 'VE Minuten',
        distanz: 'VE Meter',
        abklingzeit: 'W20 Tage',
        effekt: 'Öffnet ein Tor zu einer namentlich genannten Existenzebene. Es schließt sich, sobald VE/2 Wesen hindurchgegangen sind oder die Dauer endet.',
        seite: 63
    },
    {
        name: 'Einschläfern',
        typ: 'normal',
        geistesbeeinflussend: true,
        zugang: [{ klasse: 'heiler', stufe: 2 }, { klasse: 'schwarzmagier', stufe: 5 }, { klasse: 'zauberer', stufe: 5 }],
        preis: 45,
        zb: '-(KÖR+VE)/2 des jeweiligen Ziels',
        dauer: 'Augenblicklich',
        distanz: 'Radius von VE x 2 Meter',
        abklingzeit: '10 Kampfrunden',
        effekt: 'Versetzt bis zu Stufe viele Ziele in natürlichen Schlaf, aus dem sie durch Kampflärm u.ä. erwachen können.',
        seite: 63
    },
    {
        name: 'Elementar herbeirufen',
        typ: 'normal',
        zugang: [{ klasse: 'schwarzmagier', stufe: 16 }, { klasse: 'zauberer', stufe: 10 }],
        preis: 920,
        zb: '-Elementarstufe x 5',
        dauer: 'VE Stunden',
        distanz: 'Radius von VE Meter',
        abklingzeit: '24 Stunden',
        effekt: 'Ruft ein Elementar (Erde, Feuer, Luft oder Wasser — je ein eigener Spruch) der Elementarstufe I-III herbei; höhere Stufe senkt den ZB. Es muss VE Aufträge erfüllen.',
        seite: 63
    },
    {
        name: 'Erdspalt',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 10 }, { klasse: 'schwarzmagier', stufe: 14 }, { klasse: 'zauberer', stufe: 10 }],
        preis: 325,
        zb: '-4',
        dauer: 'VE Kampfrunden',
        distanz: 'VE x 2 Meter',
        abklingzeit: '100 Kampfrunden',
        effekt: 'Öffnet auf festem Boden einen Spalt (VE m breit, VE/2 m lang und tief). Betroffene dürfen sich mit AGI+BE aktionsfrei retten; wer beim Schließen darin ist, erleidet 2W20 nicht abwehrbaren Schaden.',
        arten: ['elementar'],
        seite: 64
    },
    {
        name: 'Federgleich',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 5 }, { klasse: 'schwarzmagier', stufe: 3 }, { klasse: 'zauberer', stufe: 3 }],
        preis: 110,
        zb: '+0',
        dauer: '1 Minute und bis Distanz gefallen',
        distanz: 'Berühren',
        abklingzeit: '0 Kampfrunden',
        effekt: 'Das Ziel gleitet aus bis zu doppeltem Probenergebnis in Metern sanft zu Boden (1m pro Kampfrunde). Der Fall muss binnen 1 Minute beginnen.',
        seite: 64
    },
    {
        name: 'Feueratem',
        typ: 'ziel',
        zugang: [{ klasse: 'schwarzmagier', stufe: 10 }, { klasse: 'zauberer', stufe: 10 }],
        preis: 460,
        zb: '+3',
        dauer: 'Augenblicklich',
        distanz: 'VE Meter',
        abklingzeit: '10 Kampfrunden',
        effekt: 'Eine Flammensäule aus dem Mund trifft alle Gegner in einer 1m breiten, geraden Schneise; nicht abwehrbarer Schaden in Höhe des Probenergebnisses.',
        arten: ['feuer', 'elementar'],
        seite: 64
    },
    {
        name: 'Feuerball',
        typ: 'ziel',
        zugang: [{ klasse: 'schwarzmagier', stufe: 10 }, { klasse: 'zauberer', stufe: 10 }],
        preis: 460,
        zb: '+3',
        dauer: 'Augenblicklich',
        distanz: 'VE x 10 Meter',
        abklingzeit: '10 Kampfrunden',
        effekt: 'Ein Feuerball explodiert im Radius von VE Metern; nicht abwehrbarer Schaden in Höhe des Probenergebnisses.',
        arten: ['feuer', 'elementar'],
        seite: 65
    },
    {
        name: 'Feuerlanze',
        typ: 'ziel',
        zugang: [{ klasse: 'schwarzmagier', stufe: 5 }, { klasse: 'zauberer', stufe: 5 }],
        preis: 210,
        zb: '+2',
        dauer: 'Augenblicklich',
        distanz: 'VE x 10 Meter',
        abklingzeit: '0 Kampfrunden',
        effekt: 'Mächtigere Variante des Feuerstrahls; Schaden = Probenergebnis.',
        arten: ['feuer', 'elementar'],
        seite: 65
    },
    {
        name: 'Feuerstrahl',
        typ: 'ziel',
        zugang: [{ klasse: 'schwarzmagier', stufe: 1 }, { klasse: 'zauberer', stufe: 1 }],
        preis: 10,
        zb: '+1',
        dauer: 'Augenblicklich',
        distanz: 'VE x 5 Meter',
        abklingzeit: '0 Kampfrunden',
        effekt: 'Ein Feuerstrahl trifft einen Feind; Schaden = Probenergebnis.',
        arten: ['feuer', 'elementar'],
        seite: 65
    },
    {
        name: 'Feuerwand',
        typ: 'normal',
        zugang: [{ klasse: 'schwarzmagier', stufe: 10 }, { klasse: 'zauberer', stufe: 8 }],
        preis: 360,
        zb: '-2',
        dauer: 'VE Kampfrunden',
        distanz: 'VE x 2 Meter',
        abklingzeit: '100 Kampfrunden',
        effekt: 'Erschafft eine Feuerwand von maximal 1m x VE m x VE m. Wer darin steht oder hindurchspringt, erleidet 2W20 abwehrbaren Schaden.',
        arten: ['feuer', 'elementar'],
        seite: 65
    },
    {
        name: 'Flackern',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 2 }, { klasse: 'schwarzmagier', stufe: 4 }, { klasse: 'zauberer', stufe: 4 }],
        preis: 45,
        zb: '-2',
        dauer: 'Probenergebnis x 2 Kampfrunden',
        distanz: 'Selbst',
        abklingzeit: '100 Kampfrunden',
        effekt: 'Der Zauberwirker flackert und erhöht seine Abwehr um GEI/2 (nicht gegen einhüllenden Flächenschaden).',
        arten: ['heilung'],
        seite: 66
    },
    {
        name: 'Flammeninferno',
        typ: 'ziel',
        zugang: [{ klasse: 'schwarzmagier', stufe: 15 }, { klasse: 'zauberer', stufe: 15 }],
        preis: 1420,
        zb: '+5',
        dauer: 'VE Kampfrunden',
        distanz: 'VE x 10 Meter',
        abklingzeit: '24 Stunden',
        effekt: 'Eine Kreisfläche mit Radius VE Meter steht in Flammen; jeder darin erleidet pro Kampfrunde nicht abwehrbaren Schaden in Höhe des Probenergebnisses.',
        arten: ['feuer', 'elementar'],
        seite: 66
    },
    {
        name: 'Flammenklinge',
        typ: 'ziel',
        zugang: [{ klasse: 'schwarzmagier', stufe: 4 }, { klasse: 'zauberer', stufe: 4 }],
        preis: 160,
        zb: '+0',
        dauer: 'Probenergebnis in Kampfrunden',
        distanz: 'VE x 2m',
        abklingzeit: '100 Kampfrunden',
        effekt: 'Hüllt eine Metallklinge in magisches Feuer: WB +1 und magischer Schaden. Ein Immersieg verdoppelt den erwürfelten Schaden dieser Kampfrunde.',
        arten: ['feuer', 'elementar'],
        seite: 66
    },
    {
        name: 'Fliegen',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 20 }, { klasse: 'schwarzmagier', stufe: 10 }, { klasse: 'zauberer', stufe: 10 }],
        preis: 460,
        zb: '+0',
        dauer: 'Probenergebnis x 5 Kampfrunden',
        distanz: 'Berühren',
        abklingzeit: '100 Kampfrunden',
        effekt: 'Das Ziel kann fliegen; die Fluggeschwindigkeit ist doppelt so hoch wie der Laufen-Wert am Boden (rennend nochmals verdoppelt).',
        seite: 66
    },
    {
        name: 'Fluch',
        typ: 'normal',
        zugang: [{ klasse: 'schwarzmagier', stufe: 2 }, { klasse: 'zauberer', stufe: 6 }],
        preis: 150,
        zb: '- (GEI+AU)/2 des Ziel',
        dauer: 'Probenergebnis Tage',
        distanz: 'Berühren',
        abklingzeit: '24 Stunden',
        effekt: 'Benötigt einen Gegenstand des Ziels, der beim Zaubern zerstört wird. Das verfluchte Ziel erhält -2 auf alle Proben; jeder Fluch muss einzeln per Magie bannen entfernt werden.',
        seite: 66
    },
    {
        name: 'Freund',
        typ: 'normal',
        geistesbeeinflussend: true,
        zugang: [{ klasse: 'heiler', stufe: 6 }, { klasse: 'schwarzmagier', stufe: 8 }, { klasse: 'zauberer', stufe: 7 }],
        preis: 370,
        zb: '-(GEI+VE)/2 des Ziels',
        dauer: 'VE Minuten',
        distanz: 'VE x 2 Meter',
        abklingzeit: '24 Stunden',
        effekt: 'Das Ziel hält den Zauberwirker für einen sehr guten Freund, vertraut ihm entsprechend und handelt entsprechend für ihn.',
        seite: 67
    },
    {
        name: 'Frostschock',
        typ: 'ziel',
        zugang: [{ klasse: 'schwarzmagier', stufe: 16 }, { klasse: 'zauberer', stufe: 12 }],
        preis: 560,
        zb: '+3',
        dauer: 'Augenblicklich',
        distanz: 'VE x 10 Meter',
        abklingzeit: '10 Kampfrunden',
        effekt: 'Ein Eisstrahl verursacht nicht abwehrbaren Schaden und friert das Ziel VE Kampfrunden ein oder bis es Schaden erhält.',
        arten: ['elementar'],
        seite: 67
    },
    {
        name: 'Frostwaffe',
        typ: 'ziel',
        zugang: [{ klasse: 'zauberer', stufe: 4 }],
        preis: 160,
        zb: '+0',
        dauer: 'Probenergebnis in Kampfrunden',
        distanz: 'VE x 2 Meter',
        abklingzeit: '100 Kampfrunden',
        effekt: 'Hüllt eine Waffe in eisige Kälte: WB +1 und magischer Schaden. Ein Immersieg friert den Gegner 1 Kampfrunde ein (wie Halt). Nicht mit Flammenklinge kombinierbar.',
        arten: ['elementar'],
        seite: 67
    },
    {
        name: 'Gasgestalt',
        typ: 'normal',
        zugang: [{ klasse: 'schwarzmagier', stufe: 18 }, { klasse: 'zauberer', stufe: 15 }],
        preis: 1420,
        zb: '+0',
        dauer: 'Probenergebnis x 5 Kampfrunden',
        distanz: 'Berühren',
        abklingzeit: '24 Stunden',
        effekt: 'Das Ziel wird samt Ausrüstung gasförmig (Laufen x 4) und passt durch kleinste Öffnungen; Zaubern, Sprechen und Angreifen sind unmöglich. Jederzeit als freie Aktion beendbar.',
        seite: 67
    },
    {
        name: 'Geben und Nehmen',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 4 }],
        preis: 115,
        zb: '+0',
        dauer: 'Probenergebnis in Kampfrunden',
        distanz: 'Berühren',
        abklingzeit: '5 Kampfrunden',
        effekt: 'Das Ziel erhält 50% des von ihm im Nahkampf verursachten Schadens (nach Abwehr des Gegners) als Heilung auf die eigene Lebenskraft.',
        seite: 68
    },
    {
        name: 'Gehorche',
        typ: 'normal',
        geistesbeeinflussend: true,
        zugang: [{ klasse: 'schwarzmagier', stufe: 10 }, { klasse: 'zauberer', stufe: 12 }],
        preis: 1120,
        zb: '-(GEI+VE)/2 des Ziels',
        dauer: 'VE/2 Kampfrunden',
        distanz: 'VE x 2 Meter',
        abklingzeit: '24 Stunden',
        effekt: 'Das Ziel wird hörig und führt jeden Befehl aus, außer Selbstmord oder Selbstverstümmelung; es greift sogar eigene Kameraden an.',
        seite: 68
    },
    {
        name: 'Giftbann',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 3 }, { klasse: 'schwarzmagier', stufe: 12 }, { klasse: 'zauberer', stufe: 6 }],
        preis: 80,
        zb: '+0',
        dauer: 'Augenblicklich',
        distanz: 'Berühren',
        abklingzeit: '10 Kampfrunden',
        effekt: 'Neutralisiert augenblicklich ein nichtmagisches Gift, sofern es nicht zu spät ist.',
        arten: ['heilung'],
        seite: 68
    },
    {
        name: 'Giftschutz',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 1 }, { klasse: 'schwarzmagier', stufe: 8 }, { klasse: 'zauberer', stufe: 2 }],
        preis: 10,
        zb: '+0',
        dauer: 'VE Stunden',
        distanz: 'Berühren',
        abklingzeit: '10 Kampfrunden',
        effekt: 'Das Ziel erhält einen Abwehr-Bonus gegen Gifte in Höhe der Stufe des Zauberwirkers; der Bonus allein wirkt auch, wo sonst keine Abwehr erlaubt ist.',
        arten: ['heilung'],
        seite: 68
    },
    {
        name: 'Glühender Glaube',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 6 }],
        preis: 185,
        zb: '-2',
        dauer: 'Probenergebnis in Kampfrunden',
        distanz: 'Berühren',
        abklingzeit: '100 Kampfrunden',
        effekt: 'Die berührte Waffe verursacht magischen Schaden, ihr WB steigt um VE/2 und die Abwehr getroffener Gegner sinkt um VE/2.',
        seite: 68
    },
    {
        name: 'Halt',
        typ: 'ziel',
        zugang: [{ klasse: 'heiler', stufe: 2 }, { klasse: 'schwarzmagier', stufe: 6 }, { klasse: 'zauberer', stufe: 6 }],
        preis: 45,
        zb: '-(KÖR+AU)/2 des Ziels',
        dauer: 'VE Kampfrunden',
        distanz: 'VE x 5 Meter',
        abklingzeit: '10 Kampfrunden',
        effekt: 'Das Ziel (keine Abwehr erlaubt) kann sich nicht mehr bewegen; die Starre endet vorzeitig bei Schaden. Atmen, Denken und Zauberwechsel bleiben möglich.',
        seite: 68
    },
    {
        name: 'Heilbeeren',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 1 }, { klasse: 'zauberer', stufe: 10 }],
        preis: 20,
        zb: '+0',
        dauer: 'Augenblicklich',
        distanz: 'Berühren',
        abklingzeit: '24 Stunden',
        effekt: 'Versieht Probenergebnis viele Beeren o.ä. mit Heilkraft (bei Druiden x 2); jede heilt 1 LK, bis zu 10 pro Aktion. Wirkung verfällt nach VE Tagen oder beim erneuten Wirken.',
        arten: ['heilung'],
        seite: 68
    },
    {
        name: 'Heilende Aura',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 1 }],
        preis: 10,
        zb: '+0',
        dauer: 'Probenergebnis x 2 Kampfrunden',
        distanz: 'Selbst',
        abklingzeit: '100 Kampfrunden',
        effekt: 'Der Heiler und alle Gefährten im Radius von VE Metern werden jede Kampfrunde um 1 LK geheilt.',
        arten: ['heilung'],
        seite: 69
    },
    {
        name: 'Heilende Hand',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 1 }],
        preis: 10,
        zb: '+1',
        dauer: 'Augenblicklich',
        distanz: 'Berühren',
        abklingzeit: '0 Kampfrunden',
        effekt: 'Heilt durch Handauflegen Lebenskraft in Höhe des Probenergebnisses.',
        arten: ['heilung'],
        seite: 69
    },
    {
        name: 'Heilende Strahlen',
        typ: 'ziel',
        zugang: [{ klasse: 'heiler', stufe: 12 }],
        preis: 395,
        zb: '+0',
        dauer: 'Augenblicklich',
        distanz: 'VE x 2 Meter',
        abklingzeit: '2 Kampfrunden',
        effekt: 'Heilt bis zu VE/2 Gefährten um das Probenergebnis. Nur eine Probe; als Malus zählt nur der Distanzmalus des am weitesten entfernten Ziels.',
        arten: ['heilung'],
        seite: 69
    },
    {
        name: 'Heilendes Feld',
        typ: 'ziel',
        zugang: [{ klasse: 'heiler', stufe: 18 }],
        preis: 1210,
        zb: '+2',
        dauer: 'Augenblicklich',
        distanz: 'Radius von VE x 2 Meter',
        abklingzeit: '24 Stunden',
        effekt: 'Heilt alle Gefährten im Wirkungsradius um das Probenergebnis.',
        arten: ['heilung'],
        seite: 69
    },
    {
        name: 'Heilendes Licht',
        typ: 'ziel',
        zugang: [{ klasse: 'heiler', stufe: 4 }],
        preis: 115,
        zb: '+2',
        dauer: 'Augenblicklich',
        distanz: 'VE x 2 Meter',
        abklingzeit: '2 Kampfrunden',
        effekt: 'Ein Lichtstrahl heilt die Lebenskraft des Ziels in Höhe des Probenergebnisses.',
        arten: ['heilung'],
        seite: 70
    },
    {
        name: 'Heiliger Hammer',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 10 }],
        preis: 1325,
        zb: '+0',
        dauer: 'VE Kampfrunden',
        distanz: 'Radius von VE x 2 Meter',
        abklingzeit: '100 Kampfrunden',
        effekt: 'Ein selbstständig kämpfender Lichthammer erscheint im Radius von VE Metern und folgt gedanklichen Kampfbefehlen; der Wirkungsbereich wandert mit dem Heiler mit.',
        seite: 70
    },
    {
        name: 'Kettenblitz',
        typ: 'ziel',
        zugang: [{ klasse: 'heiler', stufe: 16 }, { klasse: 'schwarzmagier', stufe: 10 }, { klasse: 'zauberer', stufe: 10 }],
        preis: 460,
        zb: '+3',
        dauer: 'Augenblicklich',
        distanz: 'VE x 5 Meter',
        abklingzeit: '5 Kampfrunden',
        effekt: 'Ein Blitz trifft einen Feind und springt auf bis zu VE weitere Gegner im Umkreis über. Getroffene in Metallrüstung dürfen keine Abwehr würfeln.',
        arten: ['blitz', 'elementar'],
        seite: 70
    },
    {
        name: 'Kleiner Terror',
        typ: 'normal',
        geistesbeeinflussend: true,
        zugang: [{ klasse: 'heiler', stufe: 2 }, { klasse: 'schwarzmagier', stufe: 4 }, { klasse: 'zauberer', stufe: 6 }],
        preis: 45,
        zb: '-(GEI+VE)/2 des Ziels',
        dauer: 'VE Kampfrunden',
        distanz: 'Radius von VE x 2 Meter',
        abklingzeit: '100 Kampfrunden',
        effekt: 'Bis zu Stufe/2 Ziele fliehen panisch, bis die Zauberdauer endet. Der Effekt endet für jeden Fliehenden, der Schaden erleidet.',
        seite: 70
    },
    {
        name: 'Kontrollieren',
        typ: 'normal',
        zugang: [{ klasse: 'schwarzmagier', stufe: 4 }, { klasse: 'zauberer', stufe: 8 }],
        preis: 205,
        zb: '-(GEI+AU)/2 des Ziels',
        dauer: 'Bis erlöst',
        distanz: 'VE x 2 Meter',
        abklingzeit: '10 Kampfrunden',
        effekt: 'Bringt bis zu Stufe viele Untote unter Kontrolle, auch fremd beherrschte; sie führen bedingungslos alle Befehle aus.',
        arten: ['untot'],
        seite: 70
    },
    {
        name: 'Körperexplosion',
        typ: 'ziel',
        zugang: [{ klasse: 'schwarzmagier', stufe: 20 }],
        preis: 3735,
        zb: '-(KÖR+AU)/2 des Ziels',
        dauer: 'Augenblicklich',
        distanz: 'VE Meter',
        abklingzeit: 'W20 Tage',
        effekt: 'Das Ziel explodiert: vierfaches Probenergebnis als Schaden, Abwehr ohne Panzerungsboni. Gegen körperlose Wesen nicht einsetzbar.',
        seite: 71
    },
    {
        name: 'Lauschen',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 6 }, { klasse: 'schwarzmagier', stufe: 2 }, { klasse: 'zauberer', stufe: 2 }],
        preis: 75,
        zb: '-1 pro 10m Entfernung',
        dauer: 'VE x 2 Kampfrunden',
        distanz: 'Selbst',
        abklingzeit: '100 Kampfrunden',
        effekt: 'Verlagert das Hörzentrum an einen bis zu VE x 5 Meter entfernten Punkt in Sichtlinie und hört alles, was dort zu hören ist.',
        seite: 71
    },
    {
        name: 'Licht',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 1 }, { klasse: 'schwarzmagier', stufe: 5 }, { klasse: 'zauberer', stufe: 1 }],
        preis: 10,
        zb: '+5',
        dauer: 'Probenergebnis in Minuten',
        distanz: 'Berühren',
        abklingzeit: '10 Kampfrunden',
        effekt: 'Ein berührtes, lebloses Objekt leuchtet fackelhell auf.',
        seite: 71
    },
    {
        name: 'Lichtlanze',
        typ: 'ziel',
        zugang: [{ klasse: 'heiler', stufe: 10 }, { klasse: 'zauberer', stufe: 12 }],
        preis: 325,
        zb: '+5',
        dauer: 'Augenblicklich',
        distanz: 'VE x 5 Meter',
        abklingzeit: '1 Kampfrunde',
        effekt: 'Mächtigere Variante des Lichtpfeils; Wesen der Dunkelheit erhalten -2 auf ihre Abwehr. Für Charaktere mit dem Talent Diener der Dunkelheit gesperrt.',
        seite: 71
    },
    {
        name: 'Lichtpfeil',
        typ: 'ziel',
        zugang: [{ klasse: 'heiler', stufe: 2 }, { klasse: 'zauberer', stufe: 5 }],
        preis: 45,
        zb: '+2',
        dauer: 'Augenblicklich',
        distanz: 'VE x 5 Meter',
        abklingzeit: '1 Kampfrunde',
        effekt: 'Zielzauber gegen dessen Schaden Wesen der Dunkelheit -2 auf ihre Abwehr erhalten. Für Charaktere mit dem Talent Diener der Dunkelheit gesperrt.',
        seite: 72
    },
    {
        name: 'Lichtsäule',
        typ: 'ziel',
        zugang: [{ klasse: 'heiler', stufe: 16 }, { klasse: 'zauberer', stufe: 19 }],
        preis: 535,
        zb: '+8',
        dauer: 'Augenblicklich',
        distanz: 'VE x 10 Meter',
        abklingzeit: '1 Kampfrunde',
        effekt: 'Mächtigere Variante der Lichtlanze; Wesen der Dunkelheit erhalten -2 auf ihre Abwehr. Das Talent Vergeltung addiert seinen Rang auf den PW; für Diener der Dunkelheit gesperrt.',
        seite: 72
    },
    {
        name: 'Magie bannen',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 12 }, { klasse: 'schwarzmagier', stufe: 12 }, { klasse: 'zauberer', stufe: 7 }],
        preis: 620,
        zb: '- Wirkerstufe bzw. -LK/2',
        dauer: 'Augenblicklich',
        distanz: 'VE Meter',
        abklingzeit: '24 Stunden',
        effekt: 'Bannt permanent einen Zauber oder magischen Effekt; Malus = Stufe des Wirkers bzw. LK/2 bei magischen Wesen. Gegen Wesen verursacht ein Erfolg nicht abwehrbaren Schaden statt Bannung.',
        seite: 72
    },
    {
        name: 'Magie entdecken',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 1 }, { klasse: 'schwarzmagier', stufe: 1 }, { klasse: 'zauberer', stufe: 1 }],
        preis: 10,
        zb: '+0',
        dauer: 'Probenergebnis in Kampfrunden',
        distanz: 'Radius von VE x 2 Meter',
        abklingzeit: '10 Kampfrunden',
        effekt: 'Lässt alle nicht verborgene Magie im Wirkungsbereich für den Zauberwirker kurz aufleuchten; je heller, desto mächtiger.',
        seite: 72
    },
    {
        name: 'Magie identifizieren',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 5 }, { klasse: 'schwarzmagier', stufe: 1 }, { klasse: 'zauberer', stufe: 1 }],
        preis: 10,
        zb: '+0',
        dauer: 'Augenblicklich',
        distanz: 'Berühren',
        abklingzeit: '1 Kampfrunde',
        effekt: 'Offenbart Quelle und/oder Funktion der Magie eines Objektes oder einer Örtlichkeit.',
        seite: 72
    },
    {
        name: 'Magische Barriere',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 14 }, { klasse: 'schwarzmagier', stufe: 12 }, { klasse: 'zauberer', stufe: 10 }],
        preis: 920,
        zb: '-2',
        dauer: 'VE Minuten oder Konzentration',
        distanz: 'VE x 2 Meter',
        abklingzeit: '24 Stunden',
        effekt: 'Erschafft ein unbewegliches Kraftfeld von maximal VE/2 m³, das sämtliche Magie nach innen wie außen blockt; per Konzentration verlängerbar.',
        arten: ['heilung'],
        seite: 73
    },
    {
        name: 'Magische Rüstung',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 4 }, { klasse: 'schwarzmagier', stufe: 8 }, { klasse: 'zauberer', stufe: 8 }],
        preis: 230,
        zb: '+0',
        dauer: 'Augenblicklich',
        distanz: 'Selbst',
        abklingzeit: '24 Stunden',
        effekt: 'Erhöht die Lebenskraft um das Wurfergebnis. Schaden zehrt zuerst diese (nicht heilbaren) LK auf; sie bleiben bis zum Verbrauch oder erneuten Wirken bestehen.',
        arten: ['heilung'],
        seite: 73
    },
    {
        name: 'Magische Waffe',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 1 }, { klasse: 'schwarzmagier', stufe: 1 }, { klasse: 'zauberer', stufe: 1 }],
        preis: 10,
        zb: '+0',
        dauer: 'VE Minuten',
        distanz: 'Berühren',
        abklingzeit: '1 Kampfrunde',
        effekt: 'Erhöht den WB einer Waffe um +1; ihr Schaden gilt als magisch und verletzt damit auch körperlose Wesen.',
        seite: 73
    },
    {
        name: 'Magisches Schloss',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 3 }, { klasse: 'schwarzmagier', stufe: 1 }, { klasse: 'zauberer', stufe: 1 }],
        preis: 10,
        zb: '+0',
        dauer: 'Bis Schloss geöffnet',
        distanz: 'Berühren',
        abklingzeit: '5 Kampfrunden',
        effekt: 'Verschließt Klappe, Truhe oder Tür magisch; das Probenergebnis ist die Erschwernis zum Öffnen. Auch auf mechanische Schlösser wirkend (erhöht den SW).',
        seite: 73
    },
    {
        name: 'Manabrot',
        typ: 'normal',
        zugang: [{ klasse: 'schwarzmagier', stufe: 5 }, { klasse: 'zauberer', stufe: 5 }],
        preis: 420,
        zb: '+0',
        dauer: 'Augenblicklich',
        distanz: 'VE Meter',
        abklingzeit: '24 Stunden',
        effekt: 'Erschafft bis zu Stufe/2 Laibe Manabrot; jeder entspricht einer vollen Mahlzeit (3 pro Tag und Person nötig).',
        seite: 73
    },
    {
        name: 'Nahrung zaubern',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 2 }, { klasse: 'zauberer', stufe: 7 }],
        preis: 90,
        zb: '+0',
        dauer: 'Augenblicklich',
        distanz: 'VE Meter',
        abklingzeit: '24 Stunden',
        effekt: 'Erschafft die Grundzutaten für bis zu Stufe viele einfache Mahlzeiten (3 pro Tag und Person nötig).',
        seite: 74
    },
    {
        name: 'Netz',
        typ: 'ziel',
        zugang: [{ klasse: 'heiler', stufe: 4 }, { klasse: 'schwarzmagier', stufe: 9 }, { klasse: 'zauberer', stufe: 9 }],
        preis: 115,
        zb: '-(AGI+ST)/2 des Ziels',
        dauer: 'Probenergebnis/2 Kampfrunden',
        distanz: 'VE x 5 Meter',
        abklingzeit: '10 Kampfrunden',
        effekt: 'Ein klebriges Netz mit Radius VE/2 Meter erscheint; Getroffene (keine Abwehr) halbieren Initiative, Laufen und Schlagen. Wirkungslos gegen 2+ Größenkategorien größere Wesen.',
        seite: 74
    },
    {
        name: 'Niesanfall',
        typ: 'ziel',
        zugang: [{ klasse: 'heiler', stufe: 1 }, { klasse: 'schwarzmagier', stufe: 3 }, { klasse: 'zauberer', stufe: 3 }],
        preis: 10,
        zb: '-(KÖR+AU)/2 des Ziels',
        dauer: '1 Kampfrunde',
        distanz: 'VE x 2 Meter',
        abklingzeit: '0 Kampfrunden',
        effekt: 'Das Ziel (keine Abwehr erlaubt) kann sich vor Niesen nur mit halbiertem Laufen-Wert bewegen, bis der Zauberwirker wieder an der Reihe ist; endet vorzeitig bei Schaden.',
        seite: 74
    },
    {
        name: 'Putzteufel',
        typ: 'normal',
        zugang: [{ klasse: 'schwarzmagier', stufe: 5 }, { klasse: 'zauberer', stufe: 5 }],
        preis: 420,
        zb: '+0',
        dauer: 'bis zu VE/2 Stunden',
        distanz: 'VE x 2 Meter',
        abklingzeit: '24 Stunden',
        effekt: 'Erschafft einen kleinen magischen Diener, der putzt, aufräumt und packt; er befolgt keine anderen Befehle und verpufft bei Schaden.',
        seite: 74
    },
    {
        name: 'Reinigen',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 3 }, { klasse: 'zauberer', stufe: 7 }],
        preis: 80,
        zb: '+0',
        dauer: 'Augenblicklich',
        distanz: 'Berühren',
        abklingzeit: '0 Kampfrunden',
        effekt: 'Reinigt eine Person, einen Gegenstand oder eine Mahlzeit (von Schmutz, Bakterien, Fäulnis und Gift).',
        seite: 75
    },
    {
        name: 'Rost',
        typ: 'ziel',
        zugang: [{ klasse: 'heiler', stufe: 5 }, { klasse: 'schwarzmagier', stufe: 8 }, { klasse: 'zauberer', stufe: 7 }],
        preis: 150,
        zb: '-WB der Waffe bzw. -PA der Rüstung',
        dauer: 'Augenblicklich',
        distanz: 'VE x 2 Meter',
        abklingzeit: '10 Kampfrunden',
        effekt: 'Lässt eine nichtmagische Waffe oder ein nichtmagisches Rüstungsteil aus Metall augenblicklich zu Staub zerfallen.',
        seite: 75
    },
    {
        name: 'Schatten',
        typ: 'ziel',
        zugang: [{ klasse: 'schwarzmagier', stufe: 2 }, { klasse: 'zauberer', stufe: 6 }],
        preis: 75,
        zb: '-(AGI+AU)/2 des Ziels',
        dauer: 'Probenergebnis/2 in Kampfrunden',
        distanz: 'VE x 5 Meter',
        abklingzeit: '5 Kampfrunden',
        effekt: 'Schatten umhüllen das Ziel (keine Abwehr erlaubt): -8 auf alle Handlungen, die Sehen erfordern. Wirkungslos gegen augenlose Untote und Blinde.',
        seite: 75
    },
    {
        name: 'Schatten erwecken',
        typ: 'normal',
        zugang: [{ klasse: 'schwarzmagier', stufe: 13 }],
        preis: 1580,
        zb: '+0',
        dauer: 'Augenblicklich',
        distanz: 'Radius von VE x 5 Meter',
        abklingzeit: '24 Stunden',
        effekt: 'Erweckt bis zu Stufe viele Tote im Radius als Schatten. Sie erheben sich nach drei Kampfrunden und greifen den Erwecker an, wenn er sie nicht per Kontrollieren beherrscht. Für Diener des Lichts gesperrt.',
        arten: ['untot'],
        seite: 75
    },
    {
        name: 'Schattenklinge',
        typ: 'ziel',
        zugang: [{ klasse: 'schwarzmagier', stufe: 7 }, { klasse: 'zauberer', stufe: 8 }],
        preis: 360,
        zb: '+0',
        dauer: 'Probenergebnis in Kampfrunden',
        distanz: 'VE x 2 Meter',
        abklingzeit: '100 Kampfrunden',
        effekt: 'Nur für Träger mit dem Talent Diener der Dunkelheit: WB +1, magischer Schaden, und jeder verursachte Schaden senkt die Abwehr des Ziels um 1.',
        seite: 75
    },
    {
        name: 'Schattenlanze',
        typ: 'ziel',
        zugang: [{ klasse: 'schwarzmagier', stufe: 10 }, { klasse: 'zauberer', stufe: 15 }],
        preis: 595,
        zb: '+5',
        dauer: 'Augenblicklich',
        distanz: 'VE x 10 Meter',
        abklingzeit: '0 Kampfrunden',
        effekt: 'Mächtigere Variante des Schattenpfeils; Wesen des Lichts erhalten -2 auf ihre Abwehr. Für Charaktere mit dem Talent Diener des Lichts gesperrt.',
        seite: 75
    },
    {
        name: 'Schattenpfeil',
        typ: 'ziel',
        zugang: [{ klasse: 'schwarzmagier', stufe: 2 }, { klasse: 'zauberer', stufe: 6 }],
        preis: 75,
        zb: '+2',
        dauer: 'Augenblicklich',
        distanz: 'VE x 10 Meter',
        abklingzeit: '0 Kampfrunden',
        effekt: 'Zielzauber gegen dessen Schaden Wesen des Lichts -2 auf ihre Abwehr erhalten. Für Charaktere mit dem Talent Diener des Lichts gesperrt.',
        seite: 76
    },
    {
        name: 'Schattensäule',
        typ: 'ziel',
        zugang: [{ klasse: 'schwarzmagier', stufe: 15 }, { klasse: 'zauberer', stufe: 20 }],
        preis: 920,
        zb: '+8',
        dauer: 'Augenblicklich',
        distanz: 'VE x 10 Meter',
        abklingzeit: '1 Kampfrunde',
        effekt: 'Mächtigere Variante der Schattenlanze; Wesen des Lichts erhalten -2 auf ihre Abwehr. Das Talent Vergeltung addiert seinen Rang auf den PW; für Diener des Lichts gesperrt.',
        seite: 76
    },
    {
        name: 'Schleudern',
        typ: 'ziel',
        zugang: [{ klasse: 'heiler', stufe: 18 }, { klasse: 'schwarzmagier', stufe: 10 }, { klasse: 'zauberer', stufe: 12 }],
        preis: 535,
        zb: '-(KÖR+AU)/2 des Ziels',
        dauer: 'Augenblicklich',
        distanz: 'VE/2 Meter',
        abklingzeit: '10 Kampfrunden',
        effekt: 'Schleudert das Ziel (keine Abwehr) Probenergebnis/3 Meter weit fort; es erleidet abwehrbaren Sturzschaden für die Distanz und liegt danach am Boden.',
        seite: 76
    },
    {
        name: 'Schutzfeld',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 4 }, { klasse: 'schwarzmagier', stufe: 8 }, { klasse: 'zauberer', stufe: 8 }],
        preis: 115,
        zb: '+0',
        dauer: 'Probenergebnis in Kampfrunden',
        distanz: 'Selbst',
        abklingzeit: '100 Kampfrunden',
        effekt: 'Ein Schutzfeld mit Radius VE Meter lässt nichtmagische Geschosse von außen wirkungslos abprallen.',
        arten: ['heilung'],
        seite: 76
    },
    {
        name: 'Schutzkuppel',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 8 }, { klasse: 'schwarzmagier', stufe: 12 }, { klasse: 'zauberer', stufe: 12 }],
        preis: 765,
        zb: '+0',
        dauer: 'Konzentration',
        distanz: 'Selbst',
        abklingzeit: 'W20 Tage',
        effekt: 'Eine unbewegliche Kuppel mit Radius VE Meter ist von beiden Seiten unpassierbar für Angriffe, Personen und Zauber; hält nur bei ununterbrochener Konzentration.',
        arten: ['heilung'],
        seite: 77
    },
    {
        name: 'Schutzschild',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 4 }, { klasse: 'schwarzmagier', stufe: 8 }, { klasse: 'zauberer', stufe: 8 }],
        preis: 115,
        zb: '+0',
        dauer: 'Probenergebnis in Kampfrunden',
        distanz: 'Berühren',
        abklingzeit: '100 Kampfrunden',
        effekt: 'Das Ziel erhält das Probenergebnis als Bonus auf seine Abwehr, bis die Zauberdauer abläuft.',
        arten: ['heilung'],
        seite: 77
    },
    {
        name: 'Schutzschild dehnen',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 4 }],
        preis: 230,
        zb: '+0',
        dauer: 'Augenblicklich',
        distanz: 'Berühren',
        abklingzeit: '24 Stunden',
        effekt: 'Verdoppelt die erwürfelte Dauer eines bereits auf das Ziel wirkenden Schutzschild-Zaubers.',
        arten: ['heilung'],
        seite: 77
    },
    {
        name: 'Schutzschild stärken',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 4 }],
        preis: 230,
        zb: '+0',
        dauer: 'Augenblicklich',
        distanz: 'Berühren',
        abklingzeit: '24 Stunden',
        effekt: 'Verdoppelt den Abwehr-Bonus eines bereits auf das Ziel wirkenden Schutzschild-Zaubers.',
        arten: ['heilung'],
        seite: 77
    },
    {
        name: 'Schweben',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 7 }, { klasse: 'schwarzmagier', stufe: 5 }, { klasse: 'zauberer', stufe: 5 }],
        preis: 210,
        zb: '+0',
        dauer: 'Probenergebnis in Kampfrunden',
        distanz: 'Berühren',
        abklingzeit: '0 Kampfrunden',
        effekt: 'Das Ziel kann statt zu laufen lotrecht auf und ab schweben, mit demselben Laufen-Wert wie am Boden (kein Rennen).',
        seite: 77
    },
    {
        name: 'Schweig',
        typ: 'ziel',
        zugang: [{ klasse: 'heiler', stufe: 12 }, { klasse: 'schwarzmagier', stufe: 8 }, { klasse: 'zauberer', stufe: 10 }],
        preis: 395,
        zb: '-(GEI+AU)/2 des Ziels',
        dauer: 'VE/2 Kampfrunden',
        distanz: 'VE x 2 Meter',
        abklingzeit: '100 Kampfrunden',
        effekt: 'Das Ziel (keine Abwehr erlaubt) verstummt; betroffene Zauberwirker können nur noch wortlos zaubern.',
        seite: 77
    },
    {
        name: 'Segen',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 2 }],
        preis: 90,
        zb: '+0',
        dauer: 'VE Stunden',
        distanz: 'Selbst',
        abklingzeit: '24 Stunden',
        effekt: 'Der Zauberwirker und bis zu VE x 2 Kameraden im Umkreis von VE x 2 Metern erhalten +1 auf alle Proben.',
        seite: 77
    },
    {
        name: 'Skelette erwecken',
        typ: 'normal',
        zugang: [{ klasse: 'schwarzmagier', stufe: 6 }],
        preis: 670,
        zb: '+0',
        dauer: 'Augenblicklich',
        distanz: 'Radius von VE x 5 Meter',
        abklingzeit: '24 Stunden',
        effekt: 'Erweckt bis zu Stufe viele Skelette im Radius. Sie erheben sich nach drei Kampfrunden und greifen den Erwecker an, wenn er sie nicht per Kontrollieren beherrscht. Für Diener des Lichts gesperrt.',
        arten: ['untot'],
        seite: 78
    },
    {
        name: 'Spionage',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 8 }, { klasse: 'schwarzmagier', stufe: 4 }, { klasse: 'zauberer', stufe: 6 }],
        preis: 205,
        zb: '+0',
        dauer: 'VE x 2 Kampfrunden',
        distanz: 'Selbst',
        abklingzeit: '100 Kampfrunden',
        effekt: 'Der Zauberwirker löst seine Seh- und Hörsinne vom Körper; der unsichtbare Blick bewegt sich VE Meter pro Kampfrunde und dringt durch kleinste Öffnungen.',
        seite: 78
    },
    {
        name: 'Springen',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 5 }, { klasse: 'schwarzmagier', stufe: 3 }, { klasse: 'zauberer', stufe: 2 }],
        preis: 60,
        zb: '+0',
        dauer: 'Augenblicklich',
        distanz: 'Selbst',
        abklingzeit: '10 Kampfrunden',
        effekt: 'Der Zauberwirker springt bis zu Probenergebnis/2 Meter weit (alternativ hoch oder runter) und landet sicher.',
        seite: 78
    },
    {
        name: 'Spurt',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 7 }, { klasse: 'schwarzmagier', stufe: 7 }, { klasse: 'zauberer', stufe: 7 }],
        preis: 220,
        zb: '-2',
        dauer: 'Probenergebnis in Kampfrunden',
        distanz: 'Berühren',
        abklingzeit: '100 Kampfrunden',
        effekt: 'Verdoppelt den Laufen-Wert des Ziels für die Zauberdauer.',
        seite: 78
    },
    {
        name: 'Steinwand',
        typ: 'normal',
        zugang: [{ klasse: 'schwarzmagier', stufe: 14 }, { klasse: 'zauberer', stufe: 10 }],
        preis: 920,
        zb: '-2',
        dauer: 'Augenblicklich',
        distanz: 'VE x 2 Meter',
        abklingzeit: '24 Stunden',
        effekt: 'Erschafft eine bleibende Steinwand von bis zu 1m x VE m x VE m auf festem Boden; ihre Abwehr entspricht der dreifachen Stufe des Zauberwirkers.',
        seite: 78
    },
    {
        name: 'Stolpern',
        typ: 'ziel',
        zugang: [{ klasse: 'schwarzmagier', stufe: 3 }, { klasse: 'zauberer', stufe: 4 }],
        preis: 140,
        zb: '-(AGI+AU)/2 des Ziels',
        dauer: 'Augenblicklich',
        distanz: 'VE x 5 Meter',
        abklingzeit: '100 Kampfrunden',
        effekt: 'Das Ziel (keine Abwehr erlaubt) stürzt zu Boden und lässt bei misslungener AGI+GE-Probe alles Gehaltene fallen.',
        seite: 79
    },
    {
        name: 'Stossgebet',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 5 }],
        preis: 150,
        zb: '-(KÖR+AU)/2 des Ziels',
        dauer: 'Augenblicklich',
        distanz: 'Selbst',
        abklingzeit: '100 Kampfrunden',
        effekt: 'Eine Druckwelle heiliger Macht bringt alle Gegner im Radius der doppelten Heiler-Stufe in Metern zu Fall.',
        seite: 79
    },
    {
        name: 'Tanz',
        typ: 'ziel',
        zugang: [{ klasse: 'schwarzmagier', stufe: 10 }, { klasse: 'zauberer', stufe: 8 }],
        preis: 360,
        zb: '-(GEI+AU)/2 des Ziels',
        dauer: 'VE/2 Minuten',
        distanz: 'VE x 5 Meter',
        abklingzeit: '10 Kampfrunden',
        effekt: 'Das Ziel (keine Abwehr erlaubt) kann nur noch tanzen und höchstens 1m pro Kampfrunde laufen; endet vorzeitig bei Schaden.',
        seite: 79
    },
    {
        name: 'Tarnender Nebel',
        typ: 'normal',
        zugang: [{ klasse: 'schwarzmagier', stufe: 3 }, { klasse: 'zauberer', stufe: 4 }],
        preis: 140,
        zb: '-2',
        dauer: 'VE x 2 Kampfrunden',
        distanz: 'VE x 5 Meter',
        abklingzeit: '10 Kampfrunden',
        effekt: 'Eine Nebelwolke mit Radius bis VE Meter entsteht: Angriffe auf Ziele darin sind um 8 erschwert, und alle darin haben -8 auf Proben, die Sehen erfordern. Wind kann sie verwehen.',
        seite: 79
    },
    {
        name: 'Telekinese',
        typ: 'ziel',
        zugang: [{ klasse: 'schwarzmagier', stufe: 8 }, { klasse: 'zauberer', stufe: 6 }],
        preis: 260,
        zb: '-1 pro (Stufe x 5) kg Gewicht',
        dauer: 'Konzentration',
        distanz: 'VE x 5 Meter',
        abklingzeit: '0 Kampfrunden',
        effekt: 'Lässt einen unbelebten Gegenstand mit 1m pro Kampfrunde schweben, solange der Zauberwirker sich ununterbrochen konzentriert (ganze Aktion).',
        seite: 79
    },
    {
        name: 'Teleport',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 20 }, { klasse: 'schwarzmagier', stufe: 10 }, { klasse: 'zauberer', stufe: 10 }],
        preis: 920,
        zb: '-1 pro Begleiter',
        dauer: 'Augenblicklich',
        distanz: 'Berühren',
        abklingzeit: '24 Stunden',
        effekt: 'Teleportiert den Zauberwirker und bis zu VE Begleiter an einen bekannten Ort; bei nur flüchtiger Kenntnis wird der PW halbiert. Ein Patzer verursacht W20 (bzw. 2W20) nicht abwehrbaren Schaden.',
        seite: 79
    },
    {
        name: 'Terror',
        typ: 'normal',
        geistesbeeinflussend: true,
        zugang: [{ klasse: 'heiler', stufe: 5 }, { klasse: 'schwarzmagier', stufe: 7 }, { klasse: 'zauberer', stufe: 9 }],
        preis: 300,
        zb: '-(GEI+VE)/2 des Ziels',
        dauer: 'VE Minuten',
        distanz: 'Radius von VE x 5 Meter',
        abklingzeit: '24 Stunden',
        effekt: 'Bis zu Stufe viele Ziele fliehen panisch, bis die Zauberdauer endet. Der Effekt endet für jeden Fliehenden, der Schaden erleidet.',
        seite: 80
    },
    {
        name: 'Tierbeherrschung',
        typ: 'normal',
        geistesbeeinflussend: true,
        zugang: [{ klasse: 'schwarzmagier', stufe: 8 }, { klasse: 'zauberer', stufe: 9 }],
        preis: 410,
        zb: '-LK/2 des Ziels',
        dauer: 'VE Stunden',
        distanz: 'VE x 2 Meter',
        abklingzeit: '100 Kampfrunden',
        effekt: 'Macht ein Tier zum willenlosen Sklaven, der alle einsilbigen Befehle befolgt. Höchstens VE Tiere gleichzeitig beherrschbar.',
        seite: 80
    },
    {
        name: 'Tiere besänftigen',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 1 }, { klasse: 'zauberer', stufe: 7 }],
        preis: 20,
        zb: '-LK/5 des Ziels',
        dauer: 'VE Stunden',
        distanz: 'Radius von VE x 5 Meter',
        abklingzeit: '24 Stunden',
        effekt: 'Besänftigt aggressive Tiere im Wirkungsradius. Magische Wesen und Tiere unter einem Kontrollzauber sind immun.',
        seite: 80
    },
    {
        name: 'Totengespräch',
        typ: 'normal',
        zugang: [{ klasse: 'schwarzmagier', stufe: 9 }],
        preis: 1590,
        zb: '+0',
        dauer: 'VE Fragen bzw. VE Minuten',
        distanz: 'Berühren',
        abklingzeit: 'W20 Tage',
        effekt: 'Befragt den Geist eines Toten; er antwortet auf bis zu VE Fragen mit Ja oder Nein, jedoch nicht zwingend wahrheitsgemäß.',
        seite: 80
    },
    {
        name: 'Trugbild',
        typ: 'normal',
        geistesbeeinflussend: true,
        zugang: [{ klasse: 'schwarzmagier', stufe: 7 }, { klasse: 'zauberer', stufe: 5 }],
        preis: 210,
        zb: '-2',
        dauer: 'VE/2 Stunden',
        distanz: 'VE Meter',
        abklingzeit: '100 Kampfrunden',
        effekt: 'Erschafft eine rein optische, unbewegliche Illusion von maximal VE/2 Kubikmetern. Durchschaubar mit einer Bemerken-Probe abzüglich des halbierten Probenergebnisses.',
        seite: 80
    },
    {
        name: 'Unsichtbares sehen',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 10 }, { klasse: 'schwarzmagier', stufe: 12 }, { klasse: 'zauberer', stufe: 12 }],
        preis: 325,
        zb: '+0',
        dauer: 'Probenergebnis in Kampfrunden',
        distanz: 'Berühren',
        abklingzeit: '100 Kampfrunden',
        effekt: 'Das Ziel erkennt unsichtbare Objekte und Lebewesen normal. Magische Effekte (außer dem Zauber Unsichtbarkeit) und verborgene Fallen zählen nicht als unsichtbar.',
        seite: 81
    },
    {
        name: 'Unsichtbarkeit',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 20 }, { klasse: 'schwarzmagier', stufe: 12 }, { klasse: 'zauberer', stufe: 12 }],
        preis: 1120,
        zb: '+0',
        dauer: 'Probenergebnis in Minuten',
        distanz: 'Berühren',
        abklingzeit: '24 Stunden',
        effekt: 'Macht ein Lebewesen samt getragener Ausrüstung oder ein Objekt unsichtbar. Endet vorzeitig bei Angriff, Zaubern oder erlittenem Schaden.',
        seite: 81
    },
    {
        name: 'Verborgenes sehen',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 8 }, { klasse: 'schwarzmagier', stufe: 8 }, { klasse: 'zauberer', stufe: 8 }],
        preis: 510,
        zb: '+0',
        dauer: 'Probenergebnis in Kampfrunden',
        distanz: 'Radius von VE x 2 Meter',
        abklingzeit: '24 Stunden',
        effekt: 'Lässt verborgene oder versteckte unbelebte Dinge (Fallen, Geheimtüren) im Radius aufleuchten, auch hinter Verdeckungen. Wirkt nicht bei magischen oder unsichtbaren Objekten.',
        seite: 81
    },
    {
        name: 'Verdampfen',
        typ: 'ziel',
        zugang: [{ klasse: 'schwarzmagier', stufe: 18 }, { klasse: 'zauberer', stufe: 20 }],
        preis: 2230,
        zb: '-(KÖR+AU)/2 des Ziels',
        dauer: 'Augenblicklich',
        distanz: 'VE Meter',
        abklingzeit: '24 Stunden',
        effekt: 'Das Ziel verdampft: dreifaches Probenergebnis als Schaden, Abwehr ohne Panzerungsboni. Gegen wasserlose Wesen nicht einsetzbar.',
        seite: 81
    },
    {
        name: 'Vergrößern',
        typ: 'normal',
        zugang: [{ klasse: 'schwarzmagier', stufe: 12 }, { klasse: 'zauberer', stufe: 10 }],
        preis: 920,
        zb: '-4',
        dauer: 'Probenergebnis/2 in Kampfrunden',
        distanz: 'Berühren',
        abklingzeit: '24 Stunden',
        effekt: 'Verdoppelt Körpergröße des freiwilligen Ziels samt Ausrüstung (Größenkategorie „groß“); KÖR, ST, HÄ und Laufen werden verdoppelt.',
        seite: 81
    },
    {
        name: 'Verkleinern',
        typ: 'normal',
        zugang: [{ klasse: 'schwarzmagier', stufe: 8 }, { klasse: 'zauberer', stufe: 10 }],
        preis: 460,
        zb: '-4',
        dauer: 'Probenergebnis Minuten',
        distanz: 'Berühren',
        abklingzeit: '24 Stunden',
        effekt: 'Verkleinert das freiwillige Ziel samt Ausrüstung auf ein Zehntel (Größenkategorie „winzig“); KÖR, ST und HÄ werden halbiert, Laufen durch 10 geteilt.',
        seite: 81
    },
    {
        name: 'Verlangsamen',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 3 }, { klasse: 'schwarzmagier', stufe: 8 }, { klasse: 'zauberer', stufe: 8 }],
        preis: 80,
        zb: '-(KÖR+AU)/2 des Ziels',
        dauer: 'VE Kampfrunden',
        distanz: 'Radius von VE x 5 Meter',
        abklingzeit: '10 Kampfrunden',
        effekt: 'Halbiert den Laufen-Wert von bis zu Stufe/2 vielen Zielen.',
        seite: 82
    },
    {
        name: 'Versetzen',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 10 }, { klasse: 'schwarzmagier', stufe: 6 }, { klasse: 'zauberer', stufe: 6 }],
        preis: 260,
        zb: '+0',
        dauer: 'Augenblicklich',
        distanz: 'Berühren',
        abklingzeit: '10 Kampfrunden',
        effekt: 'Teleportiert das einwilligende Ziel bis zu Probenergebnis/2 Meter weit in Sichtlinie; reicht die Distanz nicht, geht es so weit wie möglich in die Zielrichtung.',
        seite: 82
    },
    {
        name: 'Versetzte Stimme',
        typ: 'normal',
        zugang: [{ klasse: 'schwarzmagier', stufe: 3 }, { klasse: 'zauberer', stufe: 2 }],
        preis: 60,
        zb: '-1 pro 10 Meter Entfernung',
        dauer: 'VE x 2 Kampfrunden',
        distanz: 'Selbst',
        abklingzeit: '100 Kampfrunden',
        effekt: 'Verlagert das Gesagte an einen bis zu VE x 10 Meter entfernten Punkt in Sichtlinie; alle in Hörweite dieses Punktes hören den Zauberwirker.',
        seite: 82
    },
    {
        name: 'Verteidigung',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 1 }, { klasse: 'schwarzmagier', stufe: 4 }, { klasse: 'zauberer', stufe: 4 }],
        preis: 10,
        zb: '+0',
        dauer: '1 Kampfrunde',
        distanz: 'VE x 2 Meter',
        abklingzeit: '0 Kampfrunden',
        effekt: 'Das Ziel erhält das Probenergebnis als Abwehr-Bonus, bis der Zauberwirker in der nächsten Kampfrunde wieder an der Reihe ist.',
        arten: ['heilung'],
        seite: 82
    },
    {
        name: 'Vertreiben',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 1 }],
        preis: 10,
        zb: '-(KÖR+AU)/2 des Ziels',
        dauer: 'Probenergebnis/2 Minuten',
        distanz: 'Radius von VE x 2 Meter',
        abklingzeit: '100 Kampfrunden',
        effekt: 'Vertreibt bis zu Stufe/2 Untote im Wirkungsbereich auf Probenergebnis x 5 Meter Distanz; sie können solange niemanden im Wirkungsbereich angreifen. Endet bei jedem Untoten, der Schaden erleidet.',
        arten: ['untot'],
        seite: 83
    },
    {
        name: 'Verwandlung',
        typ: 'normal',
        geistesbeeinflussend: true,
        zugang: [{ klasse: 'schwarzmagier', stufe: 10 }, { klasse: 'zauberer', stufe: 5 }],
        preis: 420,
        zb: '-2',
        dauer: 'Probenergebnis/2 in Stunden',
        distanz: 'Selbst',
        abklingzeit: '24 Stunden',
        effekt: 'Der Zauberwirker nimmt das Aussehen einer anderen Person des eigenen Volkes und Geschlechts an. Bei nur flüchtig bekannten Vorbildern durchschaubar per Bemerken-Probe.',
        seite: 83
    },
    {
        name: 'Verwirren',
        typ: 'normal',
        geistesbeeinflussend: true,
        zugang: [{ klasse: 'heiler', stufe: 8 }, { klasse: 'schwarzmagier', stufe: 5 }, { klasse: 'zauberer', stufe: 5 }],
        preis: 210,
        zb: '-(GEI+AU)/2',
        dauer: 'Probenergebnis in Kampfrunden',
        distanz: 'Radius von VE x 2 Meter',
        abklingzeit: '10 Kampfrunden',
        effekt: 'Das Ziel handelt jede Kampfrunde zufällig (W20-Tabelle): Angriff auf die Charaktere, ziellos umherlaufen, herumstehen oder Angriff auf die eigenen Verbündeten.',
        seite: 84
    },
    {
        name: 'Volksgestalt',
        typ: 'normal',
        zugang: [{ klasse: 'schwarzmagier', stufe: 5 }, { klasse: 'zauberer', stufe: 5 }],
        preis: 420,
        zb: '-4',
        dauer: 'Probenergebnis in Stunden',
        distanz: 'VE Meter',
        abklingzeit: '24 Stunden',
        effekt: 'Verwandelt bis zu VE einwilligende humanoide Ziele in ein anderes humanoides Volk gleicher Größenkategorie (nicht die Ausrüstung); Fähigkeiten bleiben erhalten.',
        seite: 84
    },
    {
        name: 'Waffe des Lichts',
        typ: 'ziel',
        zugang: [{ klasse: 'heiler', stufe: 7 }, { klasse: 'zauberer', stufe: 8 }],
        preis: 220,
        zb: '+0',
        dauer: 'Probenergebnis in Kampfrunden',
        distanz: 'VE x 2 Meter',
        abklingzeit: '100 Kampfrunden',
        effekt: 'Nur für Träger mit dem Talent Diener des Lichts: WB +1, magischer Schaden, und jeder verursachte Schaden erhöht die Abwehr des Waffenträgers um 1.',
        seite: 84
    },
    {
        name: 'Wahnsinn',
        typ: 'normal',
        zugang: [{ klasse: 'schwarzmagier', stufe: 15 }],
        preis: 2850,
        zb: '-(GEI+AU)/2 des Ziels',
        dauer: 'Augenblicklich',
        distanz: 'Berühren',
        abklingzeit: 'W20 Tage',
        effekt: 'Das Ziel wird wahnsinnig, sein Geist sinkt dauerhaft. Nur Allheilung kann den Effekt aufheben — je wiederherzustellendem Punkt einmal angewendet.',
        seite: 85
    },
    {
        name: 'Wandöffnung',
        typ: 'normal',
        zugang: [{ klasse: 'schwarzmagier', stufe: 14 }, { klasse: 'zauberer', stufe: 6 }],
        preis: 260,
        zb: '+0',
        dauer: 'Probenergebnis/2 Kampfrunden',
        distanz: 'Berühren',
        abklingzeit: '100 Kampfrunden',
        effekt: 'Öffnet ein rundes Loch von 1m Durchmesser in einer bis zu VE x 10 cm dicken, nichtmagischen Steinwand; es verschwindet spurlos, wenn der Zauber endet.',
        seite: 84
    },
    {
        name: 'Wasser teilen',
        typ: 'ziel',
        zugang: [{ klasse: 'heiler', stufe: 12 }],
        preis: 1185,
        zb: '+0',
        dauer: 'Konzentration',
        distanz: 'Berühren',
        abklingzeit: 'W20 Tage',
        effekt: 'Teilt ein Gewässer auf 1m Breite bis zum Grund. Gegen flüssige Wesen eingesetzt verursacht das Wurfergebnis nicht abwehrbaren Schaden (Dauer dann augenblicklich).',
        arten: ['elementar'],
        seite: 85
    },
    {
        name: 'Wasser weihen',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 1 }],
        preis: 10,
        zb: '+0',
        dauer: 'VE Stunden',
        distanz: 'Berühren',
        abklingzeit: '24 Stunden',
        effekt: 'Verwandelt berührtes reines Wasser in Weihwasser; pro Anwendung Probenergebnis/2 Einheiten (je etwa 1/2 Liter).',
        seite: 85
    },
    {
        name: 'Wasserwandeln',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 5 }, { klasse: 'schwarzmagier', stufe: 9 }, { klasse: 'zauberer', stufe: 9 }],
        preis: 150,
        zb: '+0',
        dauer: 'VE Stunden',
        distanz: 'Berühren',
        abklingzeit: '0 Kampfrunden',
        effekt: 'Das Ziel kann Probenergebnis viele Runden lang auf Wasser laufen wie auf festem Land.',
        seite: 86
    },
    {
        name: 'Wechselzauber',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 12 }, { klasse: 'schwarzmagier', stufe: 12 }, { klasse: 'zauberer', stufe: 10 }],
        preis: 790,
        zb: '+0',
        dauer: 'Augenblicklich',
        distanz: 'Selbst',
        abklingzeit: '24 Stunden',
        effekt: 'Präpariert einen Zauberspruch, zu dem einmalig aktionsfrei gewechselt werden kann.',
        seite: 86
    },
    {
        name: 'Wiederbelebung',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 10 }],
        preis: 650,
        zb: '+0',
        dauer: 'Augenblicklich',
        distanz: 'Berühren',
        abklingzeit: '24 Stunden',
        effekt: 'Belebt einen nicht natürlich Gestorbenen (höchstens W20 Tage tot) mit 1 LK wieder; er verliert permanent 1 Punkt KÖR. Bei KÖR 1 nicht mehr möglich, Verletzungen bleiben.',
        arten: ['heilung'],
        seite: 86
    },
    {
        name: 'Wolke der Reue',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 1 }, { klasse: 'zauberer', stufe: 6 }],
        preis: 10,
        zb: '-2',
        dauer: 'Probenergebnis in Kampfrunden',
        distanz: 'VE x 5 Meter',
        abklingzeit: '100 Kampfrunden',
        effekt: 'Eine unsichtbare Wolke mit Radius bis VE Meter entsteht; jeder darin erhält -1 auf alle Proben. Wind kann sie verwehen.',
        seite: 86
    },
    {
        name: 'Wolke des Todes',
        typ: 'normal',
        zugang: [{ klasse: 'schwarzmagier', stufe: 13 }],
        preis: 790,
        zb: '-4',
        dauer: 'Probenergebnis x 2 Kampfrunden',
        distanz: 'VE x 5 Meter',
        abklingzeit: '100 Kampfrunden',
        effekt: 'Eine schwarze Wolke mit Radius bis VE Meter entsteht: Angriffe auf Ziele darin -2, Sehproben darin -2, und jeder darin erleidet pro Runde 1 nicht abwehrbaren Schaden.',
        seite: 86
    },
    {
        name: 'Wächter',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 4 }, { klasse: 'schwarzmagier', stufe: 5 }, { klasse: 'zauberer', stufe: 6 }],
        preis: 115,
        zb: '+0',
        dauer: 'VE Stunden',
        distanz: 'Berühren',
        abklingzeit: '24 Stunden',
        effekt: 'Ein magischer Wächter alarmiert bzw. weckt den Zauberwirker, sobald sich ein Wesen dem Zielpunkt auf VE x 2 Meter nähert (nicht bei bereits Anwesenden).',
        seite: 84
    },
    {
        name: 'Zauberabklang',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 10 }, { klasse: 'schwarzmagier', stufe: 9 }, { klasse: 'zauberer', stufe: 5 }],
        preis: 650,
        zb: '- eigene Zugangsstufe für den Spruch',
        dauer: 'Augenblicklich',
        distanz: 'Selbst',
        abklingzeit: '24 Stunden',
        effekt: 'Versucht die Abklingzeit eines in den letzten VE Kampfrunden erfolgreich gewirkten Zaubers auf Null zu senken. Bei Misserfolg erst nach erneutem Wirken jenes Zaubers wiederholbar.',
        seite: 87
    },
    {
        name: 'Zauberleiter',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 8 }, { klasse: 'schwarzmagier', stufe: 4 }, { klasse: 'zauberer', stufe: 4 }],
        preis: 320,
        zb: '+0',
        dauer: 'Konzentration',
        distanz: 'VE Meter',
        abklingzeit: '24 Stunden',
        effekt: 'Erschafft eine freistehende magische Leiter von bis zu VE x Stufe Metern Höhe; sie bleibt, solange der Zauberwirker sich konzentriert (ganze Aktion).',
        seite: 87
    },
    {
        name: 'Zaubertrick',
        typ: 'normal',
        zugang: [{ klasse: 'schwarzmagier', stufe: 1 }, { klasse: 'zauberer', stufe: 1 }],
        preis: 10,
        zb: '+0',
        dauer: 'Probenergebnis in Kampfrunden',
        distanz: 'VE x 2 Meter',
        abklingzeit: '10 Kampfrunden',
        effekt: 'Erzeugt kleine, unschädliche Illusionen wie schwebende Bälle oder ein Kaninchen aus dem Hut.',
        seite: 87
    },
    {
        name: 'Zeitstop',
        typ: 'normal',
        zugang: [{ klasse: 'schwarzmagier', stufe: 20 }, { klasse: 'zauberer', stufe: 15 }],
        preis: 2130,
        zb: '-5',
        dauer: 'Probenergebnis in Kampfrunden',
        distanz: 'Selbst',
        abklingzeit: 'W20 Tage',
        effekt: 'Hält die Zeit an, bis die Dauer endet oder der Zauberwirker Schaden verursacht bzw. erleidet. Andere Objekte und Lebewesen sind starr eingefroren und unbeweglich.',
        seite: 87
    },
    {
        name: 'Zombies erwecken',
        typ: 'normal',
        zugang: [{ klasse: 'schwarzmagier', stufe: 8 }],
        preis: 930,
        zb: '+0',
        dauer: 'Augenblicklich',
        distanz: 'Radius von VE x 5 Meter',
        abklingzeit: '24 Stunden',
        effekt: 'Erweckt bis zu Stufe viele Leichen im Radius als Zombies. Sie erheben sich nach drei Kampfrunden und greifen den Erwecker an, wenn er sie nicht per Kontrollieren beherrscht. Für Diener des Lichts gesperrt.',
        arten: ['untot'],
        seite: 87
    },
    {
        name: 'Öffnen',
        typ: 'normal',
        zugang: [{ klasse: 'heiler', stufe: 2 }, { klasse: 'schwarzmagier', stufe: 1 }, { klasse: 'zauberer', stufe: 1 }],
        preis: 10,
        zb: '- SW',
        dauer: 'Augenblicklich',
        distanz: 'Berühren',
        abklingzeit: '10 Kampfrunden',
        effekt: 'Öffnet ein Schloss unbeschädigt; ZB = -Schlosswert. Jeder Folgeversuch an demselben Schloss senkt den PW kumulativ um 2.',
        seite: 74
    }
];
